<?php

namespace App\Http\Livewire\Table;


use Mediconesystems\LivewireDatatables\Column;
use Mediconesystems\LivewireDatatables\Http\Livewire\LivewireDatatable;
use Mediconesystems\LivewireDatatables\NumberColumn;

class Teacher extends LivewireDatatable
{

//    public $model=\App\Models\Teacher::class;
public function builder()
{
    return \App\Models\Teacher::query(); // TODO: Change the autogenerated stub
}


public function columns()
{
    return [
        NumberColumn::name('id')->label("ID"),
        Column::name('firstname')->label("First Name"),
        Column::name('lastname')->label("Last Name"),
        NumberColumn::name('college.name')->label("COLLEGE"),
        NumberColumn::name('user.email')->label("Email"),
        Column::name('phone')->label("Phone"),
  Column::callback(['id'], function ($id) {
      return view('component.btn', ['url' => route('teacher.show',$id),'name'=>__("page.show",['name'=>trans_choice('menu.teacher',1)])]);
  })->label(__("button.view"))->width(30),
//        Column::name('firstname'),

    ]; // TODO: Change the autogenerated stub
}
}
